% Compute Approximate Designs using CVX

rng(123); % set seed for reproducability

%% INITIALIZE DESIGN WITH CVX
tic

dim = 4;
N0 = 8; % number of initial design points (N0^dim)

% design space bounds
a1 = -1; b1 = 1;

%A = [a1 a2 a3];
%B = [b1 b2 b3];

A = [a1 a1 a1 a1];
B =[b1 b1 b1 b1];

%x = setprod(linspace(a1,b1,N0),linspace(a2,b2,N0),linspace(a3,b3,N0));
% design space generated by a cartesian product
x = setprod(linspace(a1,b1,N0),linspace(a1,b1,N0),linspace(a1,b1,N0),linspace(a1,b1,N0));


% Compute components of FIM
theta = [1 1 1 1 1 1 1 1];

%% 


I0 = FIM_1d_saturated_cubic(x); 
q = size(I0,1);

%% INITIALIZE DESIGN

sc = 1;
tol = 1e-4;



cvx_begin
            cvx_precision high
            variable w(1,N0^dim); %weights
            expression Ie(q,q); %information matrix
            
            for i=1:N0^dim
                Ie = Ie+I0(:,:,i)*w(i);
            end
           
            Ie=sc*Ie;

            minimize(-log(det_rootn(Ie)))   %D-opt

            0 <= w <= 1;
            sum(w)==1;
cvx_end

toc
%initialize weights, optimal design, and objective function value
d = x(w(1,:)>tol,:);
w = w(w(1,:)>tol)'; 
L = cvx_optval;